version: '3.1'

services:
  app:
    build: .
  database:
    image: postgres:alpine
    ports:
            - '5432:5432'
    environment:
      - POSTGRES_DB=gorest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    volumes:
        - './storage/postgres:/var/lib/postgres/data'

  adminer:
        image: adminer
        ports:
            - '9000:8080'
        links:
            - 'database:db'

  consul:
        image: 'consul:latest'
        ports:
            - '8500:8500'
