#!/bin/sh

go build .
export GOREST_CONSUL_URL="127.0.0.1:8500"
export GOREST_CONSUL_PATH="gorest"
echo "ENV: GOREST_CONSUL_URL=" $GOREST_CONSUL_URL
echo "ENV: GOREST_CONSUL_PATH=" $GOREST_CONSUL_PATH
./going_rest serve -p 8080
